config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users
  resources :categories
  resources :articles
end

app/models/user.rb
class User < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include SessionsHelper
  before_action :current_user, only: :index
  before_action :redirect_if_logged_in, only: [:new, :create]
  before_action :redirect_unless_logged_in, only: [:index]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    decorator = SavingUserWithSendingMail.new(@user)

    if decorator.save
      redirect_to users_path, notice: '登録完了メールを送信しました。'
    else
      render :new
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end

    def redirect_unless_logged_in
      redirect_to login_path, notice: "ログインしてください。" and return unless logged_in?
    end
end

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :password
    = f.password_field :password
  .actions
    = f.submit 'Save'

app/views/users/index.html.haml
%h1 ユーザーリスト

%table
  %thead
    %tr
      %th 名前
      %th メールアドレス

  %tbody
    - @users.each do |user|
      %tr
        %td= user.name
        %td= user.email

%br

= link_to '新規登録', new_user_path unless @current_user

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path